<#
  Scans assets/img/highlights/ and regenerates assets/js/gallery-list.js,
  which index.html reads to build the highlights carousel.

  Run this after adding or removing images:
      pwsh tools/build-gallery.ps1

  Slides appear in filename order, so prefix names with 01-, 02-, ... to control it.

  assets/img/highlights/full/ is optional. A file there whose name matches one in
  the main folder is the full-resolution original: the gallery still shows the
  small version, and only the lightbox loads the big one when opened.
#>

$ErrorActionPreference = 'Stop'

$repoRoot  = Split-Path -Parent $PSScriptRoot
$imgDir    = Join-Path $repoRoot 'assets/img/highlights'
$outFile   = Join-Path $repoRoot 'assets/js/gallery-list.js'
$webFolder = 'assets/img/highlights/'

if (-not (Test-Path $imgDir)) {
    throw "Image folder not found: $imgDir"
}

# Filter on Extension rather than -Include: -Include silently matches nothing
# unless the path ends in \* or -Recurse is used.
$extensions = '.jpg', '.jpeg', '.png', '.webp'
$images = Get-ChildItem -Path $imgDir -File |
          Where-Object { $extensions -contains $_.Extension.ToLower() } |
          Sort-Object Name

if ($images.Count -eq 0) {
    Write-Warning "No images found in $imgDir - writing an empty list (the gallery section will hide itself)."
}

# ConvertTo-Json handles quoting/escaping of spaces and non-ASCII filenames.
# Select-Object rather than $images.Name: the latter yields $null (not an empty
# collection) when nothing matched. -InputObject rather than the pipeline: an
# empty array sends zero objects down the pipeline and emits nothing at all.
$names = @($images | Select-Object -ExpandProperty Name)
$namesJson = ConvertTo-Json -InputObject $names -Compress

# Names that also have a full-resolution twin in full/.
$fullDir = Join-Path $imgDir 'full'
$fullNames = @()
if (Test-Path $fullDir) {
    $fullNames = @(Get-ChildItem -Path $fullDir -File |
                   Where-Object { $extensions -contains $_.Extension.ToLower() -and $names -contains $_.Name } |
                   Select-Object -ExpandProperty Name |
                   Sort-Object)
}
$fullJson = ConvertTo-Json -InputObject $fullNames -Compress

$content = @"
// Generated by tools/build-gallery.ps1 - do not edit by hand.
// Re-run that script after adding or removing images in $webFolder
const galleryFolder = '$webFolder';
const galleryList = $namesJson;
// Names that have a full-resolution copy in ${webFolder}full/ (lightbox only).
const galleryFull = $fullJson;
"@

Set-Content -Path $outFile -Value $content -Encoding utf8NoBOM

Write-Host "Wrote $($images.Count) image(s) to assets/js/gallery-list.js"
foreach ($img in $images) {
    $tag = if ($fullNames -contains $img.Name) { '  [+ full-res]' } else { '' }
    Write-Host "  $($img.Name)$tag"
}
